json.extract! review, 
             :id, 
             :nickname, 
             :body, 
             :overall, 
             :food, 
             :service, 
             :ambience, 
             :value, 
             :user_id, 
             :restaurant_id, 
             :created_at, 
             :updated_at